//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tasklist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<int> id_status { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> criacao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
    
        public virtual status status { get; set; }
    }
}
